[tool.poetry]
name = "gh_browser"
version = "0.1.0"
description = ""
authors = ["Dmitry Malinovsky <damalinov@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "3.6"
flask = "^1.0"
gunicorn = "^19.9"
requests = "^2.19"

[tool.poetry.dev-dependencies]
